export const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN' ,
    ADD_ITEM : 'ADD_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART' ,
    INCREASE_ITEM_QUANTITY: 'INCREASE_ITEM_QUANTITY',
    DECREASE_ITEM_QUANTITY: 'DECREASE_ITEM_QUANTITY',
    CLEAR_CART: 'CLEAR_CART'
}